/* Generated by HeytingLean (lambda_kernel_export)
   Kernel slice: LambdaIR nat→nat fragment (verified at IR level).
*/

#include "kernel.h"
long long heyting_add1(long long x) {
  return (x + 1);
}
